project:
  type: website
  output-dir: _site

website:
  title: "Zach Bogart"
  favicon: "favicon.png"
  site-url: "https://www.zachbogart.com/"
  page-navigation: false # can loop through sections in sidebar (arrows at bottom)
  navbar:
    background: light
    left:
        - text: "A Bit About Me"
          href: about.qmd
        - text: "Everything Else"
          href: blog/index.qmd
  page-footer: 
    left: 
      - icon: heart-fill
        href: http://ko-fi.com/zachbogart
    center:
      - text: "data.start.page"
        href: https://data.start.page
    right: 
      - icon: github
        href: https://github.com/zachbogart/my_website
      - icon: twitter 
        href: https://twitter.com/zachbogart
      - icon: at 
        href: https://www.threads.net/@zbnerd
        
format:
  html:
    theme: 
      light: 
        - zephyr
        - theme.scss
    css: styles.css
    toc: true



