project:
  type: website
  output-dir: _site
format:
  html:
    theme: 
      light: 
        - zephyr
        - theme.scss
    css: styles.css
    toc: true
website:
  title: "Zach Bogart"
  favicon: "favicon.png"
  site-url: "https://www.zachbogart.com/"
  navbar:
    background: light
    left:
        - icon: circle
          text: Locally
          menu:
            - icon: house-heart
              text: Home
              href: index.qmd
            - icon: emoji-smile
              text: A bit about me
              href: about.qmd
            - icon: box
              text: Projects
              href: projects/index.qmd
            - icon: pencil-square
              text: Everything Else
              href: blog/index.qmd
        - icon: globe-americas
          text: Externally
          menu:
            - text: Projects
            - icon: heart-fill
              text: Noun Project Icons ↗️
              href: https://thenounproject.com/zachbogart/
            - icon: eye-fill
              text: Observable Profile ↗️
              href: https://observablehq.com/@zachbogart?tab=profile
            - text: Code
            - icon: github
              text: Website Repo ↗️
              href: https://github.com/zachbogart/my_website
            - text: Socials
            - icon: at
              text: Threads ↗️
              href: https://www.threads.net/@zbnerd
            - icon: twitter 
              text: Twitter ↗️
              href: https://twitter.com/zachbogart
  page-footer: 
    left: 
      - text: License
        href: https://creativecommons.org/licenses/by-sa/4.0/
    right:
      - icon: cup-hot-fill
        href: http://ko-fi.com/zachbogart



