project:
  type: website
  output-dir: _site
format:
  html:
    theme: 
      light: 
        - zephyr
        - theme.scss
    css: styles.css
    toc: true
website:
  title: "Zach Bogart"
  favicon: "favicon.png"
  site-url: "https://www.zachbogart.com/"
  navbar:
    background: light
    left:
        - icon: circle
          text: Locally
          menu:
            - icon: emoji-smile
              text: A bit about me
              href: about.qmd
            - icon: box
              text: Projects
              href: projects/index.qmd
            - icon: pencil-square
              text: Everything Else
              href: blog/index.qmd
        - icon: globe-americas
          text: Externally
          menu:
            - text: Projects
            - icon: heart-fill
              text: Noun Project Icons ↗
              href: https://thenounproject.com/zachbogart/
            - icon: eye-fill
              text: Observable Profile ↗
              href: https://observablehq.com/@zachbogart?tab=profile
            - text: Socials
            - icon: at
              text: ~~Twitter~~ X ↗
              href: https://twitter.com/zachbogart
            - icon: at
              text: Threads ↗
              href: https://www.threads.net/@zbnerd
            - text: Other
            - icon: bag-heart-fill
              text: Store ↗
              href: https://zachbogart.gumroad.com/
  page-footer: 
    left: 
      - text: License
        href: license.qmd
    center:
      - icon: github
        href: https://github.com/zachbogart/my_website
    right:
      - icon: cup-hot-fill
        href: http://ko-fi.com/zachbogart



