---
title: "Other Things"
subtitle: A loose archive of things I've gotten up to.
format:
    html:
        css: light.css
---

<!-- For icons, see https://icons.getbootstrap.com/ -->

- I'm definitely more of a cat person. And I'd say I'm a film fan. So I made [<i class="bi bi-film"></i> a Twitter account that posts clips of cats in movies, called FilmCats](https://twitter.com/filmcats). It's a manual process, but I wanted the clips all in one place, hence a feed devoted to films that have cats in them. Meow!
- Data is everywhere...even in candy. Made [<i class="bi bi-pie-chart"></i> a real-life pie chart and histogram out of M&Ms](https://twitter.com/zachbogart/status/1202779889184567298), grouped by color...I'm not OCD, you're OCD!
- Skittles do this neat color-bleed when they sit in water. Which means you can make [<i class="bi bi-droplet-half"></i> a pie chart from the Skittles candy color bleed](https://twitter.com/zachbogart/status/939647709253955584). And throw in a histogram for good measure.
- Grad school will make you do wacky things. Like [<i class="bi bi-stickies"></i> cover a dorm room wall-to-wall in hundreds of Post-It's](projects/postit-wall.html) just for the fun of it. In ~~prison~~ *grad school*, a man'll do most anything to keep his mind occupied.
- [<i class="bi bi-play-btn-fill"></i> Darn! That's the end!](https://youtu.be/YkAX7Vk3JEw?t=2m52s)

***

<div style="text-align: center;">[<i class="bi bi-question-octagon-fill" style="font-size: 16pt;"></i>](help.qmd#legibility)</div>
