---
pagetitle: "Zach Bogart"
title: "\"I'll know it when I see it\""
subtitle: A selection of things I've gotten up to
format:
  html:
    css: light.css # styling, light text
---

<!-- For icons, see https://icons.getbootstrap.com/ -->

## Work
- I work on the data team at [<i class="bi bi-bar-chart-fill"></i> Periscopic, a socially conscious data visualization firm](https://periscopic.com), where we try to do good with data.

## Hobbies
- I work with data, but I also play with data. I'm [<i class="bi bi-eye-fill"></i> making Observable Notebooks](https://observablehq.com/@zachbogart?tab=profile), which are interactive javascript notebooks that make it easy to start exploring while still allowing for amazing possibilities. Looking into these in an effort to better communicate data findings/understanding and spark curiosity. And to just have some fun.
- I started [<i class="bi bi-bezier"></i> making icons for Noun Project](projects/nouns.qmd) after wanting some icon headers for a project I worked on over the summer in grad school. Turned into a fun hobby.
-   I have made [<i class="bi bi-shop"></i> a T-shirt shop called Designed By a Nerd](projects/designedbyanerd.qmd), full of some fun ideas I wanted for myself, the kinds of things where I would want to say "hey, i like your shirt". Made with love by an outgoing introvert.

## Selected Creations
-   While in grad school at Columbia, I worked on [<i class="bi bi-bar-chart-line-fill"></i> an online resource for data visualization called edav.info](projects/edav.qmd). It's a helpful resource for learning about working and presenting data with R, all the while being generated and improved by the students.
-   I made [<i class="bi bi-book"></i> Bookworm, a way to keep track of what I'm reading](projects/bookworm.qmd) using a big 'ol Google Sheet, spruced up with Observable.
-   I tried making some collegiate notebook marginalia into a typeface, and it actually worked and you can try it. It's called [<i class="bi bi-blockquote-left"></i> Koji, a highly geometric typeface](projects/koji.qmd) I made by hand. Crazy respect for the crazy people who devote themselves to this. Also, I hate kerning sooo much.

## Randomness
- I'm definitely more of a cat person. And I'd say I'm a film fan. So I made [<i class="bi bi-film"></i> a Twitter account that posts clips of cats in movies, called FilmCats](https://twitter.com/filmcats). It's a manual process, but I wanted the clips all in one place, hence a feed devoted to films that have cats in them. Meow!
- Data is everywhere...even in candy. Made [<i class="bi bi-pie-chart"></i> a real-life pie chart and histogram out of M&Ms](https://twitter.com/zachbogart/status/1202779889184567298), grouped by color...I'm not OCD, you're OCD!
- Skittles do this neat color-bleed when they sit in water. Which means you can make [<i class="bi bi-droplet-half"></i> a pie chart from the Skittles candy color bleed](https://twitter.com/zachbogart/status/939647709253955584). And throw in a histogram for good measure.
- Grad school will make you do wacky things. Like [<i class="bi bi-stickies"></i> cover a dorm room wall-to-wall in hundreds of Post-It's](projects/postit-wall.html) just for the fun of it. In ~~prison~~ *grad school*, a man'll do most anything to keep his mind occupied.
- In college, everything you printed through the university came with a full-page receipt. So I [<i class="bi bi-file-break"></i> collected a bunch of print receipts, folded them into origami art](projects/origami.qmd), and would leave them around campus.

## Archive
- In college, I "put hats on rats", [<i class="bi bi-wrench-adjustable"></i> building implants that stuck electrodes into rodent brains to record neural activity](projects/directed-study.qmd). Unlike the common saying, it actually WAS brain surgery.
-   I sent [<i class="bi bi-envelope-heart"></i> a physical postcard of my podcast listening](projects/podcast-postcard.qmd) to FiveThirtyEight, and they had some nice things to say.
- I wanted to stay curious so I [<i class="bi bi-gem"></i> made a Twitter account posting about what is interesting and extraordinary about ordinary things](projects/extraordinary.qmd). My hope was that these tweets, in some small way, could keep you feeling interested and excited about the world we live in. Also gave some longer posts a try about nerdy things. Stay curious.
- I like video games, and that's good fodder for dataviz. I [<i class="bi bi-joystick"></i> made a viz of a Fortnite run from Ninja](projects/ninja.qmd), a streamer you probably have heard of with electric-blue hair. Was a fun early experiment using manual methods and Illustrator.

## Hard to Read?
I thought it'd be neat to use a light font color for the majority of the text on this page, letting the links draw your eye and allow you to read more if you're interested. However, that does make the text inherently harder to read and more inaccessible to some readers.

<span style="color: #FC6E61">**If you have trouble reading the text, there's a dark mode toggle at the top-right**</span> of the navigation bar that should help make the body text more legible.

***
<div style="text-align: center;">[<i class="bi bi-play-btn-fill"></i> Darn! That's the end!](https://youtu.be/YkAX7Vk3JEw?t=2m52s)</div>
