---
title: Ways to Support
author: Zach Bogart
date: '2020-05-11'
slug: support
categories: 
tags: 
subtitle: Much appreciated.
reading_time: false
image:
  caption: ''
  focal_point: ''
  preview_only: no
output: html_document
editor_options:
  chunk_output_type: console
aliases: [/support]
---

<!--Starting Blurb-->
No pressure, though. 😊

<!--Put actual work here-->

## You're Just Feeling Generous

- ☕ **[Give a Coffee](https://ko-fi.com/zachbogart) ($)**: The classic way to donate to a nerd on the internet. Head to [Kofi](https://ko-fi.com/zachbogart) and order me a digital coffee (I'll probably opt for a hot chocolate, myself). Thanks! 

## You'd Like Something in Return

- 📈 **[Get Free Stock](https://join.robinhood.com/zachb524) (0)**: If you've always wanted to start investing, but aren't sure how, here's an easy way to do so. [Sign up for Robinhood](https://join.robinhood.com/zachb524) and you'll get a free stock (could be $100+), while also throwing one my way.
- 🐙 **[Download a Noun](https://thenounproject.com/zachbogart/) (¢-$)**: I make little icons and post them to [Noun Project](https://thenounproject.com/zachbogart/). If you like that sort of thing, paying for one directly supports me. And you get a nice little icon out of the deal ([project page](https://zachbogart.com/project/nouns/)).
- 👕 **[Wear a T-shirt](https://mztees.cool/) (\$-\$\$)**: If you look great in t-shirts, I got you covered. I have a collection of nerdy designs over at [mztees.cool](https://mztees.cool/). A portion of every sale directly supports me. There are also some mugs and such if that's more your jam ([project page](https://zachbogart.com/project/mztees/)).

Thanks a bunch! 🧡

<!--Noun Image Credit-->
#### Image Credit
[humility](https://thenounproject.com/zachbogart/collection/peaceful-persons/?i=3098226) by Zach Bogart from [the Noun Project](https://thenounproject.com/)
